networks:
  yml-network:

services:
  apigatewayms:
    image: apigatewayms
    build:
      context: ./APIGatewayMS/
      dockerfile: Dockerfile
    ports:
      - 56780:8080
    environment:
      - DATABASE_MS=DatabaseService
      - RESULTS_MS=ResultsService
      - TASKS_MS=TasksService
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  databsems:
    image: databsems
    build:
      context: ./DatabseMS/
      dockerfile: Dockerfile
    ports:
      - 56782:8080
    hostname: DatabaseService
    environment:
      - TEST_VAR=test
    networks:
      - yml-network
