# Do no use "" in hostnames. That is forbidden and does not work!!!!!

services:
  rabbitmqbroker:
    image:
      rabbitmq:management
    hostname:
      rabbit_mq_broker
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  apigatewayms:
    image: apigatewayms
    build:
      context: ./APIGatewayMS/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_MS=database-service:8080
      - TASKS_MS=tasks-service:8080
      - RESULTS_MS=results-service:8080
      - STATISTICS_MS=statistics-service:8080

  databsems:
    image: databsems
    build:
      context: ./DatabseMS/
      dockerfile: Dockerfile
    hostname: database-service
    environment:
      - STATISTICS_MS=statistics-service:8080

  tasksms:
    image: tasksms
    build:
      context: ./TasksMS/
      dockerfile: Dockerfile
    hostname: tasks-service
    environment:
      - STATISTICS_MS=statistics-service:8080
    depends_on:
      - rabbitmqbroker

  composerms:
    image: composerms
    build:
      context: ./ComposerMS/
      dockerfile: Dockerfile
    hostname:
      composer-service
    environment:
      - STATISTICS_MS=statistics-service:8080
      - STEAM_WEBCRWALER_MS=steam-webcrawler:8080
    depends_on:
      - rabbitmqbroker

  resultsms:
    image: resultsms
    build:
      context: ./ResultsMS/
      dockerfile: Dockerfile
    hostname: results-service
    environment:
      - DATABASE_MS=database-service:8080
      - STATISTICS_MS=statistics-service:8080
    depends_on:
      - rabbitmqbroker

  steamwebcrawler:
    image: steamwebcrawler
    build:
      context: ./Webcrawler/SteamWebCrawler/
      dockerfile: Dockerfile
    hostname: steam-webcrawler
    environment:
      - STATISTICS_MS=statistics-service:8084

  statisticsms:
    image: statisticsms
    build:
      context: ./StatisticsMS/
      dockerfile: Dockerfile
    hostname: statistics-service
    environment:
      - STATISTICS_MS=statistics-service:8080
