#
# Build stage
#
FROM eclipse-temurin AS build

# Create directories and environment variables
ENV HOME=/usr/app/DatabseMS
RUN mkdir -p $HOME
RUN mkdir -p $HOME/target
WORKDIR $HOME

# Share src folder from host (= no copy of files) with image -> change in files will be changed in next build
ADD ./DatabseMS $HOME
ADD Data-Files /usr/app/Data-Files

# Do maven build
RUN chmod +x mvnw
RUN --mount=type=cache,target=/root/.m2 ./mvnw -f $HOME/pom.xml clean package -Ddir=$HOME/target

#
# Package stage
#
FROM eclipse-temurin
ENV HOME=/usr/app/DatabseMS
ARG JAR_FILE=$HOME/target/DatabseMS-0.0.1-SNAPSHOT.jar
COPY --from=build $JAR_FILE /app/DatabseMS-0.0.1-SNAPSHOT.jar
ENTRYPOINT java -jar /app/DatabseMS-0.0.1-SNAPSHOT.jar
