FROM httpd
ADD ./tests/browser-test/ /usr/app/tests/browser-test/
ADD ./Website/ /usr/app/Website/
WORKDIR /usr/app/tests/browser-test
RUN apt update && apt upgrade -y 
RUN apt install npm -y
RUN pwd
RUN ls
RUN ls /usr/app/
RUN ls /usr/app/Website
RUN ls /usr/app/tests
RUN ls /usr/app/tests/browser-test
RUN npm install playwright@latest
RUN npx playwright install
RUN npx playwright install-deps
RUN npx playwright test
# RUN npx playwright show-report # Do it later
