FROM ubuntu

# Install Docker
RUN apt update
RUN apt upgrade -y
RUN apt install docker.io -y

# Install Docker-Compose-Plugin
RUN DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
RUN mkdir -p $DOCKER_CONFIG/cli-plugins
RUN curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose

# Install Git
RUN apt install git -y



# Run script for checking git repository
RUN bash checkoutGitRepo.sh
