networks:
  yml-network:

services:
  rabbitmqbrokerIn:
    image:
      rabbitmq:management
    hostname:
      rabbit_mq_broker_tasks
    ports:
     - 15672:15672
     - 5672:5672

  rabbitmqbrokerOut:
    image:
      rabbitmq:management
    hostname:
      rabbit_mq_broker_results
    ports:
     - 15673:15672
     - 5673:5672

  apigatewayms:
    image: apigatewayms
    build:
      context: ./APIGatewayMS/
      dockerfile: Dockerfile
    ports:
      - 56780:8080
    environment:
      - DATABASE_MS=DatabaseService
      - TASKS_MS=TasksService
      - RESULTS_MS=ResultsService
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  composerms:
    image: composerms
    build:
      context: ./ComposerMS/
      dockerfile: Dockerfile
#    ports:
#      - 56781:8080
    hostname: composerms
    environment:
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  databsems:
    image: databsems
    build:
      context: ./DatabseMS/
      dockerfile: Dockerfile
#    ports:
#      - 56782:8080
    hostname: DatabaseService
    environment:
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  resultsms:
    image: resultsms
    build:
      context: ./ResultsMS/
      dockerfile: Dockerfile
#    ports:
#      - 56783:8080
    hostname: ResultsService
    environment:
      - DATABASE_MS=DatabaseService
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  statisticsms:
    image: statisticsms
    build:
      context: ./StatisticsMS/
      dockerfile: Dockerfile
#    ports:
#      - 56784:8080
    hostname: StatisticsService
    environment:
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  tasksms:
    image: tasksms
    build:
      context: ./TasksMS/
      dockerfile: Dockerfile
#    ports:
#      - 56785:8080
    hostname: TasksService
    environment:
      - STEAM_WEBCRWALER_MS=SteamWebcrawler
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network

  steamwebcrawler:
    image: steamwebcrawler
    build:
      context: ./Webcrawler/SteamWebCrawler/
      dockerfile: Dockerfile
#    ports:
#      - 56786:8080
    hostname: SteamWebcrawler
    environment:
      - STATISTICS_MS=StatisticsService
    networks:
      - yml-network
