# 1. try:
##
## Build stage
##
#FROM maven AS build
#WORKDIR /service
#COPY pom.xml .
#COPY src ./src
#
## build the app and download dependencies only when these are new (thanks to the cache)
#RUN --mount=type=cache,target=/root/.m2  mvn clean package -X
#
##
## Package stage
##
#FROM eclipse-temurin
#WORKDIR /service
#COPY --from=build target/APIGateway-0.0.1-SNAPSHOT.jar .
#ENTRYPOINT ["java", "-jar", "APIGateway-0.0.1-SNAPSHOT.jar"]


# 2. try:
#
# Build stage
#
FROM eclipse-temurin AS build

# Create directories and environment variables
ENV HOME=/usr/app/APIGatewayMS
RUN mkdir -p $HOME
RUN mkdir -p $HOME/target
WORKDIR $HOME

# Share src folder from host (= no copy of files) with image -> change in files will be changed in next build
ADD ./APIGatewayMS $HOME
ADD Data-Files /usr/app/Data-Files

# Do maven build
RUN chmod +x mvnw
RUN --mount=type=cache,target=/root/.m2 ./mvnw -f $HOME/pom.xml clean package -Ddir=$HOME/target

#
# Package stage
#
FROM eclipse-temurin
ENV HOME=/usr/app/APIGatewayMS
ARG JAR_FILE=$HOME/target/APIGateway-0.0.1-SNAPSHOT.jar
COPY --from=build $JAR_FILE /app/APIGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT java -jar /app/APIGateway-0.0.1-SNAPSHOT.jar
