on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
name: Inspections    
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MegaLinter
        uses: oxsecurity/megalinter@v7.7.0
        
  unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Build and Run Tests 
          #run:
        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: '**/build/test-results/test/TEST-*.xml'
            
  playwright:
    name: Playwright 🎭
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Navigate to docker-compose file
      run: cd ..
    - name: Start containers
      run: |
        sudo chmod -R 777 .
        docker compose up wordpress --detach --wait --wait-timeout 2000
    - name: Install Playwright
      run: |
        npm install playwright@latest
        npx playwright install --with-deps
        npm install --save-dev @playwright/test
    - name: Run Playwright tests
      run: |
        cd tests/browser-test
        npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests/browser-test/playwright-report/
        retention-days: 5
